### ISSUE TITLE
Test Unlocking Doesn't save

### ISSUE THREAD

**Issue by Some3141** [Cal-CS-61A-Staff/ok-client#37] opened 2015-02-01 04:31 UTC
After unlocking a couple of questions, ok exits and doesn't save the unlocked progress.

**Comment by albert12132** [comment] 2015-02-01 04:44
Any details on how to reproduce this?

**Comment by Some3141** [comment] 2015-02-01 04:47
I haven't really looked into it, but my guess is that if you exit out of a question halfway through it is definitely going to repro this. ("Ctrl +C")

**Comment by papajohn** [comment] 2015-02-01 04:47
From Youri:

I ran python3 ok -u like the specs told me to and went through unlocking
some questions and stopped after unlocking up to question2. However, when I
type in exit() it completely exits ok and doesn't give me an option to save
the questions I unlocked up until that point. I had to re-unlock them when
I was unlocking each question specifically.

**Comment by albert12132** [comment] 2015-02-01 04:51
I'm not able to reproduce this bug. Every time I type "exit()" or "Ctrl-C", it saves everything that I unlocked during that session.

**Comment by albert12132** [comment] 2015-02-07 22:13
Closing this issue because I wasn't able to reproduce it, and I haven't seen it being an issue besides this one time. I suspect it was due to some exceptions not being handled properly, which might have been fixed since then.

**Closed by albert12132** 2015-02-07 22:13 UTC
Labels: bug
