### ISSUE TITLE
Contents of test files can mysteriously be deleted

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok-client#134] opened 2015-11-12 20:17 UTC
I'm not sure why, but I've seen two students with empty test files. One was `03.py` and one was `18.py` from the `scheme` project. Is it possible that quitting `ok` can leave students with an empty file?

**Comment by albert12132** [comment] 2015-11-12 20:24
I've seen this issue over many semesters, but I've never been able to
reproduce it. If you can find a way to reproduce the error, I can take a
look.

**Comment by jeffreylu017** [comment] 2015-11-12 23:18
Oh, a student reported this to me before, but I wasn't able to reproduce it then.  I think I've semi-figured it out now though.

I wrote a solution that infinitely loops (just so I have time to react), and then tried running an OK test.  During the test, I'd spam as many keyboard interrupts as possible, and then occasionally (~10% of the time?)  this will happen:
```
~/workspace/cs61a/proj/scheme$ python3 ok -q 01
=====================================================================
Assignment: Project 4: A Scheme interpreter
OK, version v1.4.4
=====================================================================
Running tests

^C^C^CTraceback (most recent call last):
  File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 9, in <module>
  File "ok/client/cli/ok.py", line 145, in main
^C~/workspace/cs61a/proj/scheme$ ^C
~/workspace/cs61a/proj/scheme$ python3 ok -q 01
=====================================================================
Assignment: Project 4: A Scheme interpreter
OK, version v1.4.4
=====================================================================

Error loading assignment: Error importing file tests/11B.py: 'module' object has no attribute 'test'
Checking for software updates...
OK is up to date
```

It looks like if a `KeyboardInterrupt` occurs while OK is dumping tests in `ok/client/cli/ok.py`, then the test becomes an empty file.

I'm not sure why we're dumping tests, but if we absolutely need to, perhaps we could try disabling the `KeyboardInterrupt` when we are?
http://stackoverflow.com/a/21919644/5365568

**Comment by albert12132** [comment] 2015-11-12 23:21
Tests are dumped in case tests were unlocked during that session. There was
a previous Github issue involving "smart dumping" (only dumping a file if
necessary), but I never got around to it.

**Comment by kvchen** [comment] 2016-02-12 01:27
This is probably because we're interrupting a write, so the contents of the file never get flushed. What we can try doing is writing the new dump to a temporary file (this part isn't atomic, so if it fails we still have the old test file to fall back to), then replace the test file with the temporary one (this part is atomic, so we should be good if an interrupt happens). I can give this a shot - @jeffreylu017 did you have a script to simulate the problem?

**Comment by knrafto** [comment] 2016-03-13 23:31
Bump - just seen on Piazza for the Ants project

**Comment by kvchen** [comment] 2016-03-13 23:39
Relevant Piazza links:

- https://piazza.com/class/ij5ddqc0arp6r4?cid=1658

**Comment by jeffreylu017** [comment] 2016-03-15 05:47
Oops, my bad, I haven't been following my email very well.

Unfortunately, I don't have a script, but if you want to add a test for it, it would probably involve two threads, one executing [`dump_tests`](https://github.com/Cal-CS-61A-Staff/ok-client/blob/master/client/api/assignment.py#L148) and the other throwing a `KeyboardInterrupt` while `dump_tests` is running.  Following the instructions posted above is also a pretty good way of reproducing the problem, if you don't feel like writing a test at the moment though.

Kevin's solution should work for the most part, but there's still the (very small) possibility that if a student unlocks tests, and use Control-C to exit OK, they may find that they need to unlock the tests again.  I was briefly playing around with the Control-C handler linked above, but unfortunately Windows doesn't play very well with it, so never mind.

**Comment by kvchen** [comment] 2016-03-15 09:35
I think Ctrl-C forcing a redo of unlocks is acceptable behavior. In the future, I wish to move away from mutating tests entirely (except in the case of updating tests) and having a separate file store progress instead.

**Comment by knrafto** [comment] 2016-08-10 19:53
Closing in favor of #194

**Closed by knrafto** 2016-08-10 19:53 UTC
