### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#93] opened 2015-06-23 00:36 UTC
Getting ERR_CONNECTION_RESET in Chrome. Error in the terminal is unsupported operand type(s) for +: ‘int’ and ‘NoneType'. Symptoms occur after clicking accept on the google oauth page. @soumyabasu , @Sumukh , any ideas why this might happen?

@colinschoen knows more details.

**Comment by jeffreylu017** [comment] 2015-06-23 01:40
Is this a duplicate of #90?

**Comment by papajohn** [comment] 2015-06-23 01:56
Does the terminal error report a line number and file for the exception?

**Comment by colinschoen** [comment] 2015-06-23 02:24
I'll get details on this @papajohn

**Comment by Sumukh** [comment] 2015-06-23 02:39
@jeffreylu017 - I've seen this happen last semester without the SSL error.

My guess is that the local server is terminating or crashing (silently?) somewhere during the redirect. 
The terminal error isn't too interesting - it happens anytime we don't get a token.

**Comment by colinschoen** [comment] 2015-06-23 02:53
![error](https://cloud.githubusercontent.com/assets/2927722/8298033/483c857e-1918-11e5-94e8-fb26b3f1d2d3.jpg)
@papajohn  -- If this helps...

**Comment by alvinwan** [comment] 2015-06-25 03:18
@Sumukh I have no idea if this even helps; it doesn't address the issue, but it at least stops the whining? #95

**Comment by soumyabasu** [comment] 2015-06-25 22:16
@colinschoen - can you put me in touch with the student?

**Comment by colinschoen** [comment] 2015-06-28 00:08
Hi @soumyabasu. I will email you the students contact information. Thank you for following up.

**Comment by knrafto** [comment] 2016-12-27 09:15
Resolved (I hope) by #256 or other changes that have happened in the past year and a half. We'll see in the coming semester.

**Closed by knrafto** 2016-12-27 09:15 UTC
Labels: bug
