### ISSUE TITLE
Browserless Auth

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#231] opened 2016-09-22 07:11 UTC
When we can't open a browser (iPython or SSH) we should get a token via OK Oauth. 

Ok Client prints a URL that the student goes to in their browser. 

```
Go to: https://okpy.org/auth/client/343j4j324xzf9
Paste in the token: 
```

gcloud client does this quite effectively. 

Implementation details:
We should notate that this is an OK OAuth token for the get_user_email function.

**Comment by knrafto** [comment] 2016-12-15 03:40
Duplicate of #212

**Comment by knrafto** [comment] 2016-12-15 03:40
Duplicate of #212

**Closed by knrafto** 2016-12-15 03:40 UTC
